### ISSUE TITLE
White-flash when using dark mode

### ISSUE THREAD

**Issue by gikari** [LunarVim/lunarvim.org#107]
When the dark mode is enabled, the page flashes, when initially loaded or refreshed.

![Screenshot_20211020_183024](https://user-images.githubusercontent.com/14205339/138123889-c331046e-6496-4271-8597-866a81eca202.png)

**Comment by AceMouty** [comment]
Issue for this seems to come from Vuepress and some default CSS they have out of the box. There is a transition on the background color. Fix is to remove the CSS rule by using your own templates.

Purposed PR to patch issue: https://github.com/LunarVim/lunarvim.org/pull/134

Discussion [here](https://issueexplorer.com/issue/vuepress/vuepress-next/387) has a fix that seems to work. Looking at it, [Jest](https://jestjs.io/) has a similar fix, you can see it by inspecting the home page and expanding the script tag they have at the top of their body tag in the page.
