### ISSUE TITLE
about the translation work

### ISSUE THREAD

**Issue by OhaTak** [LunarVim/lunarvim.org#11]
I'd like to help translate the documentation, but where and how should I start? I'd also like to know if there's anything I should be aware of when translating.

**Comment by rebuilt** [comment]
Hello.  Thanks for the offer to translate.  [The official documentation](https://v2.vuepress.vuejs.org/guide/i18n.html#site-i18n-config) is sparse.  You might have better luck with [a tutorial like this](https://medium.com/@assitan/create-a-simple-i18n-doc-with-vuepress-abf55a8eecd0) that links to a github repo you can play around with.  

Which language(s) would you be translating to?   

Also, you should know that LunarVim is changing fast and breaking things before the 1.0 release.  After that, things should stabilize a bit.  But if you're up for it, we'd love to have translations in other languages.

**Comment by ChristianChiarulli** [comment]
I think vuepress provides something for translation

**Comment by OhaTak** [comment]
I'd like to be translating into Japanese.

Sure, it would be better to wait for LunarVim to become a bit more stable before doing a full-scale translation.
At any rate, thanks for the advice!!
