### ISSUE TITLE
Remove fade on dark mode

### ISSUE THREAD

**Issue by premell** [LunarVim/lunarvim.org#114]
The fade between dark mode and light mode looks quite good, however it makes it very jarring when you actually use the website. The website will always start out in light mode, and then transition to dark mode (if you use dark mode). So you will always be faced with a bright light page every time you open the website.

So even though the fade does look good, I don't think its worth it. People generally only choose their theme of choice once and leave it there. So the fade really only serves a purpose the few times you change the theme, while the jarring white transition will occur every time. 

I am not quite sure that removing the transition will completely remove this side effect, the website might still flash white (during a shorter duration), but it might be worth it anyways since its quite easy to do. 

The other (better way) of fixing this issue is to check if dark mode is activated before rendering the page, and then render it as dark mode from the beginning. Then you can use the transition only when the dark mode is changed with the button. Of course this is harder to implement but it might be worth it.

**Comment by Uzaaft** [comment]
I think the fade is inevetable.
In the vuepress webpage it "blink" whenever you refresh, i.e it is white and then turns black whenever you refresh. IMO lunarvim.org handled it in a great way.

**Comment by Jelledb** [comment]
I have this actually the other way around, it is super weird.

You can view a video here where the page starts out in dark mode and then transitions to white.
([Video](https://jmp.sh/4Vilhxx))

I even disabled darkMode, but this effect keeps happening.

**Comment by vonPB** [comment]
New site doesn't have this issue since the state should be saved in the users browser :)
