### ISSUE TITLE
Every section rendered twice

### ISSUE THREAD

**Issue by paulieadam** [LunarVim/lunarvim.org#136]
Hello,

When I visit [https://www.lunarvim.org/](https://www.lunarvim.org/) the sections on every page are repeated twice.
I use Chrome and Edge.

Not sure if it's related but there is also a console error  
`Hydration completed but contains mismatches.`

Below is an example from the installation page.
![www lunarvim org_01-installing html](https://user-images.githubusercontent.com/10200006/143421256-0232fc23-af1a-47fa-8b93-1f695333c157.png)

**Comment by kylo252** [comment]
It's probably a regression from https://github.com/LunarVim/lunarvim.org/pull/134

@AceMouty, any ideas?
