### ISSUE TITLE
Add documentation for setting up Angular LSP

### ISSUE THREAD

**Issue by camiloaromero23** [LunarVim/lunarvim.org#145]

**Comment by Uzaaft** [comment]
I`ll work on this. Should we consider Angular as its own language(like we do vue) or should it be underneath Typescript?

**Comment by camiloaromero23** [comment]
I think it should be as it is worked with vue, as far as I know, angular has its own language server (like vue). I think it is called angularls (Correct me if I'm wrong)

**Comment by Uzaaft** [comment]
But unlike Vue Angular files are normal typescript files. Vue files have their own file extension

**Comment by camiloaromero23** [comment]
You got a point, but usually, Angular files end up with `file.component.[ts,html,css]`. For tests `file.component.spec.ts` and for the modules `file.module.ts`. So I think it is better to split up Angular from typescript because if I want to code in typescript itself, most of the time I don't want angularls to start. I don't think you're wrong but I also got a point

**Comment by Uzaaft** [comment]
@kylo252 @abzcoding Any thoughts about the topic before I write the docs?

**Comment by abzcoding** [comment]
> @kylo252 @abzcoding Any thoughts about the topic before I write the docs?

i'd appreciate it :) nothing else , tyvm <3

**Comment by Uzaaft** [comment]
I guess a separate section it is. Opening a PR ASAP

**Comment by Uzaaft** [comment]
Anyone who has a current config where `angularls` starts in an Angular project? Could not get it to start automatically with zero config beside `:lspinstall angularls`

**Comment by Uzaaft** [comment]
@abzcoding  @camiloaromero23 Do you guys have a current confign where the `angularls` lsp starts in an Angular project?

**Comment by abzcoding** [comment]
> @abzcoding @camiloaromero23 Do you guys have a current confign where the `angularls` lsp starts in an Angular project?

sadly no 😞

**Comment by camiloaromero23** [comment]
No 😢

**Comment by Uzaaft** [comment]
@abzcoding  I think I figured out why it didn't start.
Could it be because the tsserver is prioritised higher than the angularls server?
![image](https://user-images.githubusercontent.com/48220549/148922076-974936c9-53e4-4e67-837d-a73405214158.png)
Or because it is overridden?

**Comment by abzcoding** [comment]
If a server is in the override list, you have to set up and call it explicitly.
I don’t think there is any other priority.

**Comment by haexyh** [comment]
Can someone provide any update on this?

**Comment by kylo252** [comment]
is it anything beyond this?

```lua
local opts = {}
require'lvim.lsp.manager'.setup("angularls", opts)
```

cc: @haexyh, @terr-steak

**Comment by olrtg** [comment]
> is it anything beyond this?
> 
> ```lua
> local opts = {}
> require'lvim.lsp.manager'.setup("angularls", opts)
> ```
> 
> cc: @haexyh, @terr-steak

Yeah, as far as I remember it was much more than that.. even projects before Ivy were using a different version of the lsp.. vscode handles this for the user with the Angular extension. And also if I'm not mistaken a project for example with Angular 12 should also use the lsp in v12.x.x. I remember giving up on this on march of this year 😓

**Comment by olrtg** [comment]
@kylo252 can you assign this to me though? I'd like to give this a try once again.

**Comment by olrtg** [comment]
> is it anything beyond this?
> 
> ```lua
> local opts = {}
> require'lvim.lsp.manager'.setup("angularls", opts)
> ```
> 
> cc: @haexyh, @terr-steak

Well.. it seem to work just with this 😅 
Now, there will be probably some problems still with projects pre Ivy (< v9, released in 2020) due to this https://github.com/neovim/nvim-lspconfig/issues/1155#issuecomment-900850735

About the docs.. @kylo252 should I put this documentation inside de "Languages" category? Asking because Angular is not a programming language 👀 or should I add a new "Frameworks" category and maybe move Vue with it?

**Comment by kylo252** [comment]
> Now, there will be probably some problems still with projects pre Ivy (< v9, released in 2020) due to this https://github.com/neovim/nvim-lspconfig/issues/1155#issuecomment-900850735

here are some problems we need to address in the docs
- how about the interaction with tsserver, does it need to be disabled? 
- what about css servers?
- anything useful that null-ls can provide?

> About the docs.. @kylo252 should I put this documentation inside the "Languages" category? Asking because Angular is not a programming language 👀 or should I add a new "Frameworks" category and maybe move Vue with it?

this seems like a question for @ChristianChiarulli and @vonPB :)

**Comment by olrtg** [comment]
> here are some problems we need to address in the docs
> 
> * how about the interaction with tsserver, does it need to be disabled?
> * what about css servers?
> * anything useful that null-ls can provide?

@kylo252 tsserver should be enabled since you'll still using typescript.. AFAIK angularls gives completion for component templates, so in reality angularls will be working most of the time with the html lsp.

In terms of css Angular can use plain css, a pre-processor like SASS or something else like tailwindcss.. or what is your question?

For null-ls nothing that I know of.

**Comment by vonPB** [comment]
Since we got more than just Angular as a framework, I wouldn't mind having an additional frameworks page :)
