### ISSUE TITLE
copy to clipboard button inside code block doesn't work

### ISSUE THREAD

**Issue by qvieth** [LunarVim/lunarvim.org#195]
![image](https://user-images.githubusercontent.com/71810726/171313312-6e148e74-84e3-44e9-9a9c-5eca6810d0e5.png)

![image](https://user-images.githubusercontent.com/71810726/171313374-e3b7f7ce-ec57-417e-a3ab-d74f9fc7e3c3.png)

nothing happens when clicking on the button

Browser: Firefox 100.0.2 (64-bit)

**Comment by danielo515** [comment]
Didn't noticed there was such button. Maybe it should make more visible too?

**Comment by olrtg** [comment]
@qvieth can you try this again with the new docs?

**Comment by qvieth** [comment]
the issue is fixed!
