### ISSUE TITLE
Is the spanish translation a good idea? 

### ISSUE THREAD

**Issue by Nojipiz** [LunarVim/lunarvim.org#209]
I can translate all the documentation to spanish and maintain it (something like one day per week) but, it is a good idea? 
Thanks!

**Comment by Nojipiz** [comment]
So, has been past 12 days and no one seems to be interested, i will close this :P

**Comment by olrtg** [comment]
I can also help with this if needed.. I like the idea 🤘🏽

**Comment by Nojipiz** [comment]
@olrtg I just closed the issue due no one is interested :c 
Anyways, i think that the project can reach more people with this translation

**Comment by Carlos-Carsdfj** [comment]
I can help with the translation of some documentation in my free time.
