### ISSUE TITLE
"Search" does not appear to index all pages

### ISSUE THREAD

**Issue by avalonv** [LunarVim/lunarvim.org#216]
refrencing [this comment](https://github.com/LunarVim/lunarvim.org/issues/252) on the main repo.

Search does not appear to index all pages, particularly the Core Plugins page. Searching for "tree-nvim", returns only "nvim-treesitter-context", which is in Extra Plugins:
![image](https://user-images.githubusercontent.com/29720696/185721845-b3e7e02b-457a-4f6d-a1e0-cff327459777.png)

When searching "file", "explorer", no results are shown.

**Comment by vonPB** [comment]
resolved in #260
![image](https://user-images.githubusercontent.com/65032978/197337706-b3412b03-1935-45f2-aaf7-76f055021bdf.png)
