### ISSUE TITLE
[HACKTOBERFEST] add links to different lanuage setups to home page

### ISSUE THREAD

**Issue by ChristianChiarulli** [LunarVim/lunarvim.org#232]
![image](https://user-images.githubusercontent.com/29136904/193485159-173f9976-4e61-438b-bc35-77df70553313.png)
^^ like this

**Comment by mateusabelli** [comment]
Hello @ChristianChiarulli, do you mean a grid like the image for quick access on those languages setup right? just another question is it supposed to live on https://www.lunarvim.org/languages/ or https://www.lunarvim.org/?

**Comment by vonPB** [comment]
@mateusabelli Yes, I believe its supposed to be on `/` (the landing page) just below the preview screenshots.
We could either link directly to the language page in the docs or maybe to the different branches on [starter.lvim](https://github.com/LunarVim/starter.lvim/). I'm not sure if it is planned to replace the languages with starter.lvim..

**Comment by mateusabelli** [comment]
Thanks for explaining @vonPB,
Why did you close this issue @mhmdali102?

**Comment by vonPB** [comment]
@mateusabelli  He already created something like this here.. https://github.com/LunarVim/lunarvim.org/commit/2841e7675720c004a1aa3cdfd706c56ef197ba49

Sorry if you already started! Feel free to submit changes to it though if you can improve something!

**Comment by mateusabelli** [comment]
Oh that's okay, no problem. I'll take a look to see if I can submit something to improve. Thanks again @vonPB
