### ISSUE TITLE
navbar icons changing to boxes when scrolling down

### ISSUE THREAD

**Issue by vonPB** [LunarVim/lunarvim.org#238]
https://user-images.githubusercontent.com/65032978/193670492-d7681093-385a-403c-af18-e74212b77cdc.mp4

happens in chrome and edge on windows

**Comment by mhmdali102** [comment]
Hopefully this will do the trick, let me know if it fixes the issue...

**Comment by vonPB** [comment]
@mhmdali102 works just fine now, awsome :)
