### ISSUE TITLE
Docs for configuring Lunarvim for Ansible

### ISSUE THREAD

**Issue by bartheerman** [LunarVim/lunarvim.org#290]
Is it possible to add instruction for Ansible to the Languages section of the docs?

**Comment by Z3rio** [comment]
Hello!
What do you mean with "Ansible"?

**Comment by bartheerman** [comment]
I opened a ticket for adding Ansible to the list of supported languages on the website (https://github.com/LunarVim/LunarVim/issues/3451). It can be added manually, but I think it is a good idea to have it on the list of supported languages on the website.

**Comment by Z3rio** [comment]
Ah okay, I will go ahead and PR it :)

**Comment by Z3rio** [comment]
You mean to add it to this section, correct?
![image](https://user-images.githubusercontent.com/54480523/200939068-77d2a7d2-a04f-4cad-bedf-f2abe096b93d.png)

**Comment by bartheerman** [comment]
yes

**Comment by mhmdali102** [comment]
I can add it to the languages section, but need someone to write the docs for it.

**Comment by bartheerman** [comment]
Is this sufficiant:

```
# Ansible

## Install Syntax Highlighting
`:TSInstall yaml`

## Supported language servers
`{ "ansiblels" }`

## Supported linters
`{ "ansible-lint", "yamllint" }`

## Additional information about the language server
https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#ansiblels
```

**Comment by mhmdali102** [comment]
cool @bartheerman !
open pr for this and I'll merge and add Ansible for languages section

**Comment by mhmdali102** [comment]
or @Z3rio if you want

**Comment by Z3rio** [comment]
This has been fixed and can now be closed as resolved.
