### ISSUE TITLE
Conjure (Clojure and lisp) plugin keybindings 

### ISSUE THREAD

**Issue by rawoke083** [LunarVim/lunarvim.org#320]
Hi 
Congrats in LunarVim, it looks and feel awesome :)

Im trying to setup/use LunarVim with Clojure. Im using 'Conjure'  NeoVim plugin. Ive managed to 'load' it but where do I assign the keybindings and commands like ConjureConnect, ConjureEval etc ?

**Comment by vonPB** [comment]
@rawoke083 is this resolved?
