### ISSUE TITLE
Chinese translation

### ISSUE THREAD

**Issue by yuesong-feng** [LunarVim/lunarvim.org#350]
Working on the Chinese translation of this website.

**Comment by LostNeophyte** [comment]
As a heads up I'm going to refactor the docs quite heavily, I'll add, move, and delete sections, so I think it would be better to wait with the translation so you don't waste your time translating something that will be changed

**Comment by yuesong-feng** [comment]
Ok, thanks for the reminder👌

**Comment by LostNeophyte** [comment]
tracking issue for the refactor:  #352

**Comment by LostNeophyte** [comment]
most pages are ready now (unless they're marked with `This page needs improvement`), translate only the current version (/docs and not /versioned_docs).

Thank you!

**Comment by yuesong-feng** [comment]
Copy that. The pages will be ready soon.
