### ISSUE TITLE
Do you still accept document translations?

### ISSUE THREAD

**Issue by hexWars** [LunarVim/lunarvim.org#390]
### Feature Description

There is already a Chinese document, but it still not perfect.
I'm busy recently, if possible, I will pr documents before July.

**Comment by LostNeophyte** [comment]
we do, thanks for the interest, just make sure you're working on the [master version](https://www.lunarvim.org/zh-Hans/docs/master/installation) and not [1.2](https://www.lunarvim.org/zh-Hans/docs/installation)

**Comment by hexWars** [comment]
Hello,I am translating the Chinese docs, but I found that the plugin part has been deleted, does the plugin part still need to be translated?
