### ISSUE TITLE
Update for for changes in Nerdfont version 3.x

### ISSUE THREAD

**Issue by cstrahan** [LunarVim/lunarvim.org#417]
Nerdfont v3.x introduced some backwards incompatible changes (they moved some code-points around, etc).

See:

- https://github.com/nvim-tree/nvim-web-devicons/pull/264
- https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.0

Also, a recent [`wezterm`](https://wezfurlong.org/wezterm) release ([20230712-072601-f4abf8fd](https://wezfurlong.org/wezterm/changelog.html#20230712-072601-f4abf8fd)) bumped its bundled Nerdfont fallback to v3.0.1, so people depending on `wezterm` to provide the icon glyphs will have their `lvim` icons not render correctly.

And, of course, this will also apply to both `wezterm` *and* non-`wezterm` users who install the latest Nerdfont patched fonts.

**Comment by LostNeophyte** [comment]
yea, we already took care of it, did we miss something?

**Comment by cstrahan** [comment]
Files that fail [`nerdfix`](https://github.com/loichyan/nerdfix):

```bash
~/.local/share/lunarvim
% nerdfix check --recursive . 2>&1 | rg 'lazy/opt/(.*?)/' -or '$1' | sort -u
Comment.nvim
LuaSnip
alpha-nvim
bigfile.nvim
bufferline.nvim
cmp-buffer
cmp-cmdline
cmp-nvim-lsp
cmp-path
cmp_luasnip
friendly-snippets
gitsigns.nvim
indent-blankline.nvim
lazy.nvim
lir.nvim
lualine.nvim
lunar.nvim
mason-lspconfig.nvim
mason.nvim
neodev.nvim
nlsp-settings.nvim
null-ls.nvim
nvim-autopairs
nvim-cmp
nvim-dap
nvim-dap-ui
nvim-lspconfig
nvim-navic
nvim-tree.lua
nvim-treesitter
nvim-ts-context-commentstring
nvim-web-devicons
onedarker.nvim
plenary.nvim
project.nvim
schemastore.nvim
structlog.nvim
telescope-fzf-native.nvim
telescope.nvim
toggleterm.nvim
tokyonight.nvim
vim-illuminate
which-key.nvim
```

`nerdfix` will provide suggestions for to partially automate replacing old symbols.

We should probably ping these plugins' maintainers, and link back here.

---

Also, FWIW, I just installed LunarVim today via

```bash
LV_BRANCH='release-1.3/neovim-0.9' bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh)
```

**Comment by cstrahan** [comment]
Plugins to notify/fix:

- [ ] Comment.nvim
- [ ] LuaSnip
- [ ] alpha-nvim
- [ ] bigfile.nvim
- [ ] bufferline.nvim
- [ ] cmp-buffer
- [ ] cmp-cmdline
- [ ] cmp-nvim-lsp
- [ ] cmp-path
- [ ] cmp_luasnip
- [ ] friendly-snippets
- [ ] gitsigns.nvim
- [ ] indent-blankline.nvim
- [ ] lazy.nvim
- [ ] lir.nvim
- [ ] lualine.nvim
- [ ] lunar.nvim
- [ ] mason-lspconfig.nvim
- [ ] mason.nvim
- [ ] neodev.nvim
- [ ] nlsp-settings.nvim
- [ ] null-ls.nvim
- [ ] nvim-autopairs
- [ ] nvim-cmp
- [ ] nvim-dap
- [ ] nvim-dap-ui
- [ ] nvim-lspconfig
- [ ] nvim-navic
- [ ] nvim-tree.lua
- [ ] nvim-treesitter
- [ ] nvim-ts-context-commentstring
- [ ] nvim-web-devicons
- [ ] onedarker.nvim
- [ ] plenary.nvim
- [ ] project.nvim
- [ ] schemastore.nvim
- [ ] structlog.nvim
- [ ] telescope-fzf-native.nvim
- [ ] telescope.nvim
- [ ] toggleterm.nvim
- [ ] tokyonight.nvim
- [ ] vim-illuminate
- [ ] which-key.nvim

**Comment by cstrahan** [comment]
What prompted this issue was me thinking the snippet symbol in use was deprecated (I thought it was rendering wrong), but I was mistaken.

```
Icon: 
Class: nf-cod-symbol_snippet
UTF: \ueb66
```

**Comment by cstrahan** [comment]
> yea, we already took care of it, did we miss something? also this is a repo for the website, did you mean to make the issue in lunarvim/lunarvim?

Oops - yes. And I didn't see your message until now (after refreshing browser tab).
