### ISSUE TITLE
Docs not clear on how to install formatters and linters

### ISSUE THREAD

**Issue by tejasn14** [LunarVim/lunarvim.org#71]
Hey great work on lunar vim!

In the `lunarvim.org/docs/languages/typescript.md` it just says 

`The configured formatter(s) must be installed separately.` and `The configured linter must be installed separately.` 

**I feel it would be really helpful for those new to lunarvim if the docs were updated with instructions on how to  install the formatter and linter**

the same for the other language docs too(eg.`lunarvim.org/docs/languages/javascript.md`) and the main readme.md(`lunarvim.org/docs/languages/README.md`)

**Comment by daniel-vera-g** [comment]
> Hey great work on lunar vim!
> 
> In the `lunarvim.org/docs/languages/typescript.md` it just says
> 
> `The configured formatter(s) must be installed separately.` and `The configured linter must be installed separately.`
> 
> **I feel it would be really helpful for those new to lunarvim if the docs were updated with instructions on how to install the formatter and linter**
> 
> the same for the other language docs too(eg.`lunarvim.org/docs/languages/javascript.md`) and the main readme.md(`lunarvim.org/docs/languages/README.md`)

Hmm, in the Formatting section of the [Languages](https://www.lunarvim.org/languages/#formatting) page is a link to all supported linters/formatters. From there you could go to the official page and install it.  
If you wanted to directly document the instructions you should do it for all languages(not only js/ts) and they could become outdated if the installation method changes. Also sometimes there are different supported linters/formatters for a language.

**Comment by tejasn14** [comment]
how about having a section (maybe only for the js and ts) that says:
> we recommend `prettier` for the formatter and `eslint_d` for the linter. 
If you have npm installed, install both using `npm i -g prettier eslint_d` 


This is just a suggestion, as it would greatly help beginners getting lunarvim up and running. 

And if it get outdated which the npm counterparts hopefully should not change much, you can expect another issue 😜
