### ISSUE TITLE
Adding a troubleshooting tab

### ISSUE THREAD

**Issue by premell** [LunarVim/lunarvim.org#77]
I think we should add a tab to the website for common problems people encounter, like fonts not showing up, getting permission errors when installing lunarvim etc

**Comment by kylo252** [comment]
I've added this page a while ago: https://www.lunarvim.org/troubleshooting/

Feel free to send PR to update the page with any relevant problems.

**Comment by chase** [comment]
@kylo252 The page has broken links in several places

**Comment by 1inuxoid** [comment]
As @chase already mentioned, the navigation sidebar on the left on the [Troubleshooting page](https://www.lunarvim.org/troubleshooting/) contains broken links pointing to https://www.lunarvim.org/troubleshooting/01-installing.md and https://www.lunarvim.org/troubleshooting/02-after-install.md.

I have zero experience with VuePress though, but if someone can point out to how navigation is configured, I can suggest a fix 😅.

**Comment by olrtg** [comment]
@kylo252 I think we can close this 🤔

**Comment by vonPB** [comment]
@olrtg think so too :)
